// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krpidcjtiicjqndxaxyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycGlkY2p0aWljanFuZHhheHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzkxNDUsImV4cCI6MjA2NDYxNTE0NX0.ro1aD5cVOE3GppRf9pQC-HCX_1YCAKdJeS_qMbbh21g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);